//! Compares uniform vs population-weighted simplification at the same ε
//! ceiling: it reports stored-vertex counts binned by local density, plus
//! the asset size delta. The visual comparison lives in the live viewer
//! (regenerated by
//! `visualize`), which has a per-layer pop-weight toggle and the density
//! heatmap.
//!
//! ```text
//! utz_dev_cli density-compare [ds] [eps_m] [w_min]
//! ```

use utz_build::density::DensityGrid;
use utz_encode::encode::{self, Codec, Params};
use utz_encode::topo;
use utz_simplify::DensityWeight;

#[derive(clap::Args)]
pub struct Args {
    /// The dataset, one of [land-]now|1970|all.
    #[arg(default_value = "now")]
    ds: String,
    /// The simplification tolerance in meters.
    #[arg(default_value_t = 500.0)]
    eps_m: f64,
    /// The weighted-floor multiplier at max density.
    #[arg(default_value_t = 0.1)]
    density_weight_floor: f64,
}

/// # Errors
/// The command fails on a dataset load/parse, density-grid load, or encode
/// failure.
///
/// # Panics
/// The command panics if a vertex's density sample matches no band: the
/// bands cover all of `0.0..`, so only a NaN or negative sample can do
/// that.
pub fn run(args: Args) -> utz_build::Result<()> {
    // stored vertices binned by the density at the vertex itself
    const BANDS: [(f64, f64, &str); 4] = [
        (0.0, 5.0, "<5 (empty)"),
        (5.0, 100.0, "5-100 (rural)"),
        (100.0, 1000.0, "100-1k (town)"),
        (1000.0, f64::INFINITY, ">=1k (city)"),
    ];
    let (dataset, eps_m, w_min) = (args.ds, args.eps_m, args.density_weight_floor);

    let features = utz_build::load(&dataset)?;
    let grid = DensityGrid::load(&utz_build::cache_dir())?;
    let model = DensityWeight::new(w_min);

    let eps_deg = eps_m / 111_320.0;
    let topology_uniform = topo::build_topology(&features, eps_deg);
    let topology_weighted = topo::build_topology_weighted(
        &features,
        topo::Simplify::Rdp { eps: eps_deg },
        &|start, end| model.weight(grid.max_along(start, end)),
    );

    let hist = |topology: &topo::Topology| -> [usize; 4] {
        let mut histogram = [0usize; 4];
        for arc in &topology.arc_coords {
            for &(x, y) in arc {
                let density = grid.sample(x, y);
                histogram[BANDS
                    .iter()
                    .position(|band| density >= band.0 && density < band.1)
                    .unwrap()] += 1;
            }
        }
        histogram
    };
    let (hist_uniform, hist_weighted) = (hist(&topology_uniform), hist(&topology_weighted));

    println!(
        "{dataset} · RDP ε {eps_m} m ceiling · weighted floor ×{w_min} (ε {} m)\n",
        eps_m * w_min
    );
    println!(
        "{:>16} {:>10} {:>10} {:>9}",
        "density band", "uniform", "weighted", "delta"
    );
    for (i, band) in BANDS.iter().enumerate() {
        println!(
            "{:>16} {:>10} {:>10} {:>+9}",
            band.2,
            hist_uniform[i],
            hist_weighted[i],
            hist_weighted[i].cast_signed() - hist_uniform[i].cast_signed()
        );
    }
    let (sum_uniform, sum_weighted) = (
        hist_uniform.iter().sum::<usize>(),
        hist_weighted.iter().sum::<usize>(),
    );
    #[expect(
        clippy::cast_precision_loss,
        reason = "vertex-count band sums ≪ 2^53; % delta display"
    )]
    let pct = 100.0 * (sum_weighted as f64 / sum_uniform as f64 - 1.0);
    println!(
        "{:>16} {sum_uniform:>10} {sum_weighted:>10} {:>+9}  ({pct:+.1}%)\n",
        "total",
        sum_weighted.cast_signed() - sum_uniform.cast_signed()
    );

    // container size delta (same knobs, zstd; topologies already built above)
    let params = Params {
        dataset: 0,
        tzbb_release: "density-compare",
        eps_m,
        quant_bits: 24,
        grid_deg: 2.0,
        codec: Codec::Zstd,
        simplify: encode::SimplifyAlgo::default(),
        density_weight_floor: None,
        geom: encode::GeomEncoding::default(),
    };
    let container = |topology: &topo::Topology,
                     weight_floor: Option<f64>|
     -> utz_build::Result<Vec<u8>> {
        let params = Params {
            density_weight_floor: weight_floor,
            ..params
        };
        Ok(encode::finish(
            &encode::payload_from_topology(topology, &topology.arc_coords, &features, &params)?.0,
            params.codec,
        )?)
    };
    let container_uniform = container(&topology_uniform, None)?;
    let container_weighted = container(&topology_weighted, Some(w_min))?;
    #[expect(
        clippy::cast_precision_loss,
        reason = "container sizes ≪ 2^53; KiB and % display"
    )]
    let (kib_uniform, kib_weighted, kib_pct) = (
        container_uniform.len() as f64 / 1024.0,
        container_weighted.len() as f64 / 1024.0,
        100.0 * (container_weighted.len() as f64 / container_uniform.len() as f64 - 1.0),
    );
    println!(
        "container (i24, zstd): uniform {kib_uniform:.1} KiB -> weighted {kib_weighted:.1} KiB ({kib_pct:+.1}%)"
    );
    Ok(())
}
