//! The host-side μTZ lookup bench. It uses the same harness
//! (`utz_bench_common`) and the same deterministic points as the ESP32-S3
//! firmware, so host and target numbers (and answer checksums) are directly
//! comparable.
//!
//! ```text
//! cargo run --release -p utz_bench_cli -- <shape|asset.utz> [npts] [rounds]
//! ```
//!
//! `npts` uniform lon/lat points (default 100 000) are looked up once per
//! round; after one untimed warmup, the fastest of `rounds` timed rounds
//! (default 5) is reported, along with a checksum over the answers.
//!
//! The first argument is a `.utz` file path, or one of these built-in
//! shapes (assets embedded at build time):
//!
//! | shape | asset |
//! |-------|-------|
//! | `tiny`, `compact`, `balanced`, `accurate` | the presets, compressed as shipped |
//! | `tiny-static`                             | the uncompressed preset |
//! | `compact-none`, `balanced-none`           | preset recipe, uncompressed |
//! | `tiny-fixed-static`, `compact-fixed-none` | uncompressed, fixed-width arcs |
//! | `tiny-full-rings-static`, `compact-full-rings-static` | uncompressed, full rings |
//! | `tiny-coarse`                             | uncompressed, grid only (cell precision) |
//!
//! The presets come from the `utz_data_*` crates via the `utz` preset
//! features; the rest are generated by `utz_bench_common`'s `build.rs`
//! through the consumer [`utz_build::Config`] API, each changing one
//! geometry/codec knob so a run isolates that axis.
//!
//! [`utz_build::Config`]: ../utz_build/config/struct.Config.html

use std::time::Instant;

use clap::Parser;
// the shared custom shapes: uncompressed preset twins across all geometry
// encodings (recipes + capability guards in utz_bench_common's build.rs)
use utz_bench_common::assets::{
    BALANCED_NONE, COMPACT_FIXED, COMPACT_FULL_RINGS, COMPACT_NONE, TINY_COARSE, TINY_FIXED,
    TINY_FULL_RINGS,
};

/// The embedded asset for a shape name, if the argument is one.
fn embedded(name: &str) -> Option<&'static [u8]> {
    Some(match name {
        "tiny" => utz::data::TINY,
        "tiny-static" => utz::data::TINY_STATIC,
        "tiny-fixed-static" => TINY_FIXED,
        "tiny-full-rings-static" => TINY_FULL_RINGS,
        "tiny-coarse" => TINY_COARSE,
        "compact" => utz::data::COMPACT,
        "compact-none" => COMPACT_NONE,
        "compact-fixed-none" => COMPACT_FIXED,
        "compact-full-rings-static" => COMPACT_FULL_RINGS,
        "balanced" => utz::data::BALANCED,
        "balanced-none" => BALANCED_NONE,
        "accurate" => utz::data::ACCURATE,
        _ => return None,
    })
}

#[derive(Parser)]
#[command(
    name = "utz_bench_cli",
    about = "μTZ lookup benchmark over a built-in shape or .utz asset"
)]
struct Args {
    /// The built-in shape name (a preset: tiny, tiny-static, compact,
    /// balanced, accurate; or an uncompressed variant: compact-none,
    /// balanced-none, tiny-fixed-static, compact-fixed-none,
    /// tiny-full-rings-static, compact-full-rings-static, tiny-coarse; the crate docs
    /// table explains each) or a .utz asset path.
    asset: String,
    /// The number of uniform lon/lat sample points.
    #[arg(default_value_t = 100_000)]
    npts: usize,
    /// The number of timed rounds (the fastest wins; one untimed warmup
    /// pass runs first).
    #[arg(default_value_t = 5)]
    rounds: usize,
}

/// The workspace error pattern (see `utz::Error`): the enum derives its
/// traits with `derive_more`, and foreign errors convert in via
/// `derive_more::From`.
#[derive(Debug, derive_more::Display, derive_more::Error, derive_more::From)]
enum Error {
    Io(std::io::Error),
    #[display("decode: {_0}")]
    Utz(utz::Error),
}

fn main() -> Result<(), Error> {
    let args = Args::parse();
    let bytes = match embedded(&args.asset) {
        Some(embedded_bytes) => embedded_bytes.to_vec(),
        None => std::fs::read(&args.asset)?,
    };
    let size = bytes.len();
    let finder = utz::Finder::from_vec(bytes)?;
    #[expect(clippy::cast_precision_loss, reason = "asset size ≪ 2^53; KiB display")]
    let size_kib = size as f64 / 1024.0;
    println!(
        "{}: {size_kib:.1} KiB asset, tzbb release {:?}",
        args.asset,
        finder.tzbb_release()
    );

    let points = utz_bench_common::gen_pts(args.npts);
    let start = Instant::now();
    let mut now_us = move || u64::try_from(start.elapsed().as_micros()).expect("elapsed fits u64");
    let result = utz_bench_common::run_rounds(&finder, &points, args.rounds, &mut now_us);
    println!(
        "{} lookups · {} hits · {} µs · {:.3} µs/lookup · {:.0} lookups/s · checksum {}",
        result.lookups,
        result.hits,
        result.elapsed_us,
        result.us_per_lookup(),
        1e6 / result.us_per_lookup(),
        result.checksum
    );
    Ok(())
}
